name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild VSITE-Zavrsni-Rad.sln /p:Configuration=Release /p:Platform=x64